### ISSUE TITLE
一些疑问

### ISSUE THREAD

**Issue by Chorer** [thesadabc/hexo-myadmin#2]
静态博客是否可以使用？以及是否可以加入导出成md文件的功能，方便文章发布在其他博客平台

**Comment by xjpin** [comment]
@Chorer  

hexo的文章在底层就是以md文件作为存储方式的，如果不设置的话，默认路径就是在`source`文件夹， 可以直接到这个目录下面取出来就是md了。

因为上面这个原因， 文章发布编辑需要操作文件，所以静态博客用不了。
