### ISSUE TITLE
能否添加一键生成静态文件的功能

### ISSUE THREAD

**Issue by liaohui5** [thesadabc/hexo-myadmin#4]
能否添加一键生成静态文件的功能

**Comment by xjpin** [comment]
@liaohui5   不好意思哦   这个插件是要配合`hexo-server`在线服务用的  

如果站点是静态站点   不建议使用这个插件  可以使用命令[hexo generate](https://hexo.io/zh-cn/docs/generating)直接就能生成静态文件

不过可以考虑增加一个页面    来专门执行这些命令   欢迎提交PR

**Comment by Snowflake-Pink** [comment]
可以把 hexo-admin 的一键部署功能迁移过来吗？
