### ISSUE TITLE
hexo-admin中的metadata配置功能能否实现

### ISSUE THREAD

**Issue by hezhefly** [thesadabc/hexo-myadmin#5]
我的Blog想配置一些自定义字段，hexo-admin是通过配置_config.yml实现的，这个包能否也实现

**Comment by xjpin** [comment]
> 我的Blog想配置一些自定义字段，hexo-admin是通过配置_config.yml实现的，这个包能否也实现

终于抽空重构了项目

_config配置修改已经实现啦 😂😂
