### ISSUE TITLE
Invalid salt revision

### ISSUE THREAD

**Issue by elfbin-2** [thesadabc/hexo-myadmin#7]
When I login，It pops up “Invalid salt revision”!
But,my password was right，why???
My password:123456
My password_hash: $2b$12$zS69JRn6bnnbidBUw/t77OPxoeS/bqAt8mcsi1rjodK04XQZMsHbi

**Comment by YuriSizuku** [comment]
I also have this problem. Do you solve it?

**Comment by xjpin** [comment]
[bcrypt-nodejs](https://www.npmjs.com/package/bcrypt-nodejs) is a deprecated module,  can't match some hash.

`hexo-myadmin` migrate to [bcryptjs](https://www.npmjs.com/package/bcryptjs) now.

```js
const bcrypt = require("bcrypt-nodejs");
bcrypt.compareSync("123456", "$2b$12$zS69JRn6bnnbidBUw/t77OPxoeS/bqAt8mcsi1rjodK04XQZMsHbi");
// Uncaught 'Invalid salt revision'


const bcrypt = require("bcryptjs");
bcrypt.compareSync("123456", "$2b$12$zS69JRn6bnnbidBUw/t77OPxoeS/bqAt8mcsi1rjodK04XQZMsHbi");
// TRUE
```
