### ISSUE TITLE
vue vue-router 的 CDN 链接失效

### ISSUE THREAD

**Issue by liuxy0551** [thesadabc/hexo-myadmin#9]
当前 vue 最新版本为 3.x，https://unpkg.com/vue/dist/vue.min.js 会无法访问，因为最新版本 改成了 vue.global.prod.js，但是项目内使用的是 vue2.x，所以需要指定版本。

vue 改为 https://unpkg.com/vue@2.6.14/dist/vue.min.js
vue-router 同理改为 https://unpkg.com/vue-router@3.5.3/dist/vue-router.min.js

**Comment by xjpin** [comment]
已修复
